<a href="https://colab.research.google.com/github/Pratibha123-eng/data-science-and-machine-learning/blob/support-vector-machine/bangolre_house_prediction_SVR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# load dataset

In [ ]:
import pandas as pd
import numpy as np
path=r"https://drive.google.com/uc?export=download&id=1xxDtrZKfuWQfl-6KA9XEd_eatitNPnkB"
df=pd.read_csv(path)
df.head()
df.tail()

,bath,balcony,price,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
7115,3.0,2.0,325.00,2900.0,3,11206.896552,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7116,3.0,1.0,84.83,1780.0,3,4765.730337,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7117,2.0,1.0,48.00,880.0,2,5454.545455,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
7118,2.0,1.0,55.00,1000.0,2,5500.000000,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7119,2.0,1.0,78.00,1400.0,3,5571.428571,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
X=df.drop('price',axis=1)
y=df['price']
print("shape of x",X.shape)
print("shape of y",y.shape)

shape of x (7120, 107)
shape of y (7120,)

# train and split

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=2,random_state=51)
print("shape of X_train",X_train.shape)
print("shape of Y_train",y_train.shape)
print("shape of X_test",X_test.shape)
print("shape of y_test",y_test.shape)

shape of X_train (7118, 107)
shape of Y_train (7118,)
shape of X_test (2, 107)
shape of y_test (2,)

# feature scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(X_train)
X_train_sc=sc.transform(X_train)
X_test_sc=sc.transform(X_test)

# svr- rbf

In [ ]:
from sklearn.svm import SVR
from sklearn.metrics import r2_score
svr=SVR(kernel='rbf')
svr.fit(X_train_sc,y_train)
y_pred=svr.predict(X_test_sc)
r2_score(y_test,y_pred)

0.22202102894419828

# svr- linear

In [ ]:
svr=SVR(kernel='linear')
svr.fit(X_train_sc,y_train)
y_pred=svr.predict(X_test_sc)
r2_score(y_test,y_pred)

0.8868708808774299

# svr-polynomial

In [ ]:
svr=SVR(kernel='poly',degree=2)
svr.fit(X_train_sc,y_train)
y_pred=svr.predict(X_test_sc)
r2_score(y_test,y_pred)

0.24023441656232947

price prediction

In [ ]:
svr=SVR(kernel='linear')
svr.fit(X_train_sc,y_train)
y_pred=svr.predict(X_test_sc)
y_pred

array([86.48009603, 33.03496943])

In [ ]:
y_test

2435    80.0
3113    40.0
Name: price, dtype: float64

In [ ]:
r2_score(y_pred,y_test)

0.9366308082386671

# root mean square error

In [ ]:
from sklearn.metrics import mean_squared_error
import math
mse=mean_squared_error(y_test,y_pred)
rmse=math.sqrt(mse)
mse

45.251647649028044

In [ ]:
rmse

6.7269344912098