<a href="https://colab.research.google.com/github/Pratibha123-eng/data-science-and-machine-learning/blob/k-nearsest-neighbour/K_nearest_neighbour_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# import libraries

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
path=r"https://drive.google.com/uc?export=download&id=1xxDtrZKfuWQfl-6KA9XEd_eatitNPnkB"
df=pd.read_csv(path)
df.head()
df.tail(6)

,bath,balcony,price,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
7114,6.0,1.584376,390.00,3800.0,6,10263.157895,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7115,3.0,2.000000,325.00,2900.0,3,11206.896552,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7116,3.0,1.000000,84.83,1780.0,3,4765.730337,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7117,2.0,1.000000,48.00,880.0,2,5454.545455,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
7118,2.0,1.000000,55.00,1000.0,2,5500.000000,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7119,2.0,1.000000,78.00,1400.0,3,5571.428571,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
X=df.drop('price',axis=1)
y=df['price']
print("shape of x",X.shape)
print("shape of y",y.shape)

shape of x (7120, 107)
shape of y (7120,)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=2,random_state=51)
print("shape of X_train",X_train.shape)
print("shape of Y_train",y_train.shape)
print("shape of X_test",X_test.shape)
print("shape of y_test",y_test.shape)

shape of X_train (7118, 107)
shape of Y_train (7118,)
shape of X_test (2, 107)
shape of y_test (2,)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(X_train)
X_train_sc=sc.transform(X_train)
X_test_sc=sc.transform(X_test)

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
knr=KNeighborsRegressor(n_neighbors=5)
knr.fit(X_train,y_train)
knr.score(X_test,y_test)

0.9994556

# prediction

In [ ]:
X_pred=X_test.iloc[-1,:]

In [ ]:
y_pred=knr.predict([X_pred])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(

In [ ]:
y_pred

array([39.928])

In [ ]:
y_test.iloc[-1]

np.float64(40.0)

In [ ]:
df.iloc[-1,:]

bath                              2.0
balcony                           1.0
price                            78.0
total_sqft_int                 1400.0
bhk                               3.0
                                ...
location_Hosur Road               0.0
location_Horamavu Banaswadi       0.0
location_Domlur                   0.0
location_Mahadevpura              0.0
location_Tumkur Road              0.0
Name: 7119, Length: 108, dtype: float64

In [ ]:
X_test.iloc[-1,:]

bath                              2.000000
balcony                           2.000000
total_sqft_int                 1016.000000
bhk                               2.000000
price_per_sqft                 3937.007874
                                  ...
location_Hosur Road               0.000000
location_Horamavu Banaswadi       0.000000
location_Domlur                   0.000000
location_Mahadevpura              0.000000
location_Tumkur Road              0.000000
Name: 3113, Length: 107, dtype: float64

In [ ]:
y_test.iloc[-1]

np.float64(40.0)